<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Paket extends Seeder
{
    public function run()
    {
        $data = [
            // prewedding
            [
                'id_paket' => 1,
                'nama_paket' => 'Pre-Wedding Package Indoor',
                'harga_paket' => 450000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '60-90 menit',
                'jumlah_foto' => '60-120 foto',
                'jumlah_foto_edit' => '15 foto edit',
                'cetak_foto' => 'Cetak 10RS 5 lembar & Cetak 12RS + frame 1 lembar',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => "Prewedding indoor adalah sesi pemotretan yang dilakukan di dalam ruangan, seperti studio fotografi, gedung bersejarah, atau tempat-tempat tertentu yang memiliki estetika menarik. Dalam prewedding indoor, fokus utama adalah mengabadikan momen romantis antara pasangan sebelum hari pernikahan mereka.",
            ],
            [
                'id_paket' => 2,
                'nama_paket' => 'Pre-Wedding Outdoor Package A Photo',
                'harga_paket' => 1000000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '50 photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => "Prewedding outdoor adalah sesi pemotretan yang dilakukan di luar ruangan, biasanya di lokasi alam terbuka seperti taman, pantai, hutan, pegunungan, atau tempat-tempat indah lainnya. Tujuannya adalah untuk menangkap momen romantis antara pasangan dalam lingkungan alam yang indah.",
            ],
            [
                'id_paket' => 3,
                'nama_paket' => 'Pre-Wedding Outdoor Package B Photo',
                'harga_paket' => 1500000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '4 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => "Prewedding outdoor adalah sesi pemotretan yang dilakukan di luar ruangan, biasanya di lokasi alam terbuka seperti taman, pantai, hutan, pegunungan, atau tempat-tempat indah lainnya. Tujuannya adalah untuk menangkap momen romantis antara pasangan dalam lingkungan alam yang indah.",
            ],
            [
                'id_paket' => 4,
                'nama_paket' => 'Pre-Wedding Outdoor Package C Photo + Video',
                'harga_paket' => 2500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => "Prewedding outdoor adalah sesi pemotretan yang dilakukan di luar ruangan, biasanya di lokasi alam terbuka seperti taman, pantai, hutan, pegunungan, atau tempat-tempat indah lainnya. Tujuannya adalah untuk menangkap momen romantis antara pasangan dalam lingkungan alam yang indah.",
            ],
            [
                'id_paket' => 5,
                'nama_paket' => 'Pre-Wedding Outdoor Package D Photo + Video',
                'harga_paket' => 3500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Cetak 16RS + Frame',
                'videografi' => '3 minute cinematic video, video drone',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => "Prewedding outdoor adalah sesi pemotretan yang dilakukan di luar ruangan, biasanya di lokasi alam terbuka seperti taman, pantai, hutan, pegunungan, atau tempat-tempat indah lainnya. Tujuannya adalah untuk menangkap momen romantis antara pasangan dalam lingkungan alam yang indah.",
            ],
            // wedding
            ////akad
            [
                'id_paket' => 6,
                'nama_paket' => 'Akad Simple Package',
                'harga_paket' => 1350000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 25 lembar (4R) & Cetak 1x 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Akad adalah salah satu upacara penting dalam pernikahan di mana pasangan secara resmi menyatakan janji untuk menjadi suami istri di hadapan saksi-saksi dan pihak yang berwenang. Upacara akad biasanya dilaksanakan di hadapan seorang penghulu, pendeta, atau pemimpin agama sesuai dengan keyakinan dan tradisi pasangan.',
            ],
            [
                'id_paket' => 7,
                'nama_paket' => 'Akad Premium Package',
                'harga_paket' => 1750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Akad adalah salah satu upacara penting dalam pernikahan di mana pasangan secara resmi menyatakan janji untuk menjadi suami istri di hadapan saksi-saksi dan pihak yang berwenang. Upacara akad biasanya dilaksanakan di hadapan seorang penghulu, pendeta, atau pemimpin agama sesuai dengan keyakinan dan tradisi pasangan.',
            ],
            [
                'id_paket' => 8,
                'nama_paket' => 'Akad Exclusive Package',
                'harga_paket' => 2250000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Magnetic Album + 120 photo (4R)',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Akad adalah salah satu upacara penting dalam pernikahan di mana pasangan secara resmi menyatakan janji untuk menjadi suami istri di hadapan saksi-saksi dan pihak yang berwenang. Upacara akad biasanya dilaksanakan di hadapan seorang penghulu, pendeta, atau pemimpin agama sesuai dengan keyakinan dan tradisi pasangan.',
            ],
            ////resepsi
            [
                'id_paket' => 9,
                'nama_paket' => 'Resepsi Bronze Package',
                'harga_paket' => 1750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Resepsi pernikahan adalah acara yang diadakan setelah upacara akad nikah untuk merayakan pernikahan pasangan dengan keluarga, kerabat, dan teman-teman mereka. Resepsi biasanya berlangsung di tempat yang lebih luas, seperti gedung pernikahan, hotel, atau aula, dan bisa mencakup berbagai elemen seperti makanan, hiburan, dan tarian.',
            ],
            [
                'id_paket' => 10,
                'nama_paket' => 'Resepsi Silver Package Resepsi + Temu',
                'harga_paket' => 2150000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '8 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Resepsi pernikahan adalah acara yang diadakan setelah upacara akad nikah untuk merayakan pernikahan pasangan dengan keluarga, kerabat, dan teman-teman mereka. Resepsi biasanya berlangsung di tempat yang lebih luas, seperti gedung pernikahan, hotel, atau aula, dan bisa mencakup berbagai elemen seperti makanan, hiburan, dan tarian.',
            ],
            [
                'id_paket' => 11,
                'nama_paket' => 'Resepsi Gold Package Resepsi + Akad',
                'harga_paket' => 2750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '7 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Premium Magazine & print 16RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Resepsi pernikahan adalah acara yang diadakan setelah upacara akad nikah untuk merayakan pernikahan pasangan dengan keluarga, kerabat, dan teman-teman mereka. Resepsi biasanya berlangsung di tempat yang lebih luas, seperti gedung pernikahan, hotel, atau aula, dan bisa mencakup berbagai elemen seperti makanan, hiburan, dan tarian.',
            ],
            [
                'id_paket' => 12,
                'nama_paket' => 'Resepsi Platinum Package Resepsi + Akad',
                'harga_paket' => 3000000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '7 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 120 photo (4R)',
                'videografi' => '1 minute video teaser',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Resepsi pernikahan adalah acara yang diadakan setelah upacara akad nikah untuk merayakan pernikahan pasangan dengan keluarga, kerabat, dan teman-teman mereka. Resepsi biasanya berlangsung di tempat yang lebih luas, seperti gedung pernikahan, hotel, atau aula, dan bisa mencakup berbagai elemen seperti makanan, hiburan, dan tarian.',
            ],
            [
                'id_paket' => 13,
                'nama_paket' => 'Resepsi Titanium Package Resepsi + Akad',
                'harga_paket' => 4000000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '8 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Premium Magazine',
                'videografi' => '1 minute video teaser & 3 minute video highlight',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Resepsi pernikahan adalah acara yang diadakan setelah upacara akad nikah untuk merayakan pernikahan pasangan dengan keluarga, kerabat, dan teman-teman mereka. Resepsi biasanya berlangsung di tempat yang lebih luas, seperti gedung pernikahan, hotel, atau aula, dan bisa mencakup berbagai elemen seperti makanan, hiburan, dan tarian.',
            ],
            // personal indoor
            [
                'id_paket' => 14,
                'nama_paket' => 'Personal Package Indoor',
                'harga_paket' => 150000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minutes',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => '2 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => 'Photoshoot personal adalah sesi pemotretan yang difokuskan pada individu atau subjek tunggal, dengan tujuan menghasilkan foto-foto yang menampilkan kepribadian, keindahan, atau ekspresi unik dari subjek tersebut. Photoshoot personal dapat dilakukan di dalam ruangan atau di luar ruangan, tergantung pada preferensi dan tema yang diinginkan.',
            ],
            // personal outdoor
            [
                'id_paket' => 15,
                'nama_paket' => 'Personal Package Outdoor',
                'harga_paket' => 600000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'unlimited',
                'jumlah_foto_edit' => 'All photos edited tone',
                'cetak_foto' => '2 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot personal adalah sesi pemotretan yang difokuskan pada individu atau subjek tunggal, dengan tujuan menghasilkan foto-foto yang menampilkan kepribadian, keindahan, atau ekspresi unik dari subjek tersebut. Photoshoot personal dapat dilakukan di dalam ruangan atau di luar ruangan, tergantung pada preferensi dan tema yang diinginkan.',
            ],
            // group outdoor
            [
                'id_paket' => 16,
                'nama_paket' => 'Group Package Outdoor',
                'harga_paket' => 600000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'unlimited',
                'jumlah_foto_edit' => 'All photos edited tone',
                'cetak_foto' => '2 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            // group indoor
            [
                'id_paket' => 17,
                'nama_paket' => 'Group Package Indoor',
                'harga_paket' => 150000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => 'Cetak 4R/orang',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            // maternity
            [
                'id_paket' => 18,
                'nama_paket' => 'Maternity Package',
                'harga_paket' => 250000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => '5 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => 'Fotografi maternity adalah jenis fotografi yang berkaitan dengan kehamilan, di mana seorang ibu hamil akan diabadikan dalam foto-foto yang indah dan artistik.',
            ],
            // graduation indoor
            [
                'id_paket' => 19,
                'nama_paket' => 'Graduation Package Indoor',
                'harga_paket' => 275000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '1 working hours',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '15 photo edited',
                'cetak_foto' => '',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot wisuda indoor adalah sesi pemotretan yang dilakukan di dalam ruangan, biasanya di studio fotografi atau lokasi indoor lainnya, untuk mengabadikan momen spesial wisuda seseorang. Sesi ini bertujuan untuk merayakan keberhasilan dan prestasi individu yang telah menyelesaikan pendidikan mereka.',
            ],
            // graduation outdoor
            [
                'id_paket' => 20,
                'nama_paket' => 'Graduation Package Outdoor Basic',
                'harga_paket' => 250000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '1 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '10 photo edited',
                'cetak_foto' => '',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            [
                'id_paket' => 21,
                'nama_paket' => 'Graduation Package Outdoor Premium',
                'harga_paket' => 350000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '15 photo edited',
                'cetak_foto' => '',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            [
                'id_paket' => 22,
                'nama_paket' => 'Graduation Package Outdoor Exclusive',
                'harga_paket' => 500000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '50 photo edited',
                'cetak_foto' => '1x print 10RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            [
                'id_paket' => 23,
                'nama_paket' => 'Graduation Package Outdoor Exclusive + Video',
                'harga_paket' => 750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '50 photo edited',
                'cetak_foto' => '1x print 10RS + Frame',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Photoshoot group adalah sesi pemotretan yang melibatkan beberapa orang sebagai subjek dalam satu frame foto. Ini bisa melibatkan keluarga, teman, tim kerja, atau kelompok lainnya yang ingin mengabadikan momen bersama mereka.',
            ],
            // family
            [
                'id_paket' => 24,
                'nama_paket' => 'Family Package',
                'harga_paket' => 275000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => 'Cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'Indoor only',
                'deskripsi_paket'  => 'Fotografi keluarga adalah jenis fotografi yang berkaitan dengan momen-momen berharga antara anggota keluarga, di mana keluarga akan diabadikan dalam foto-foto yang indah dan mengesankan.',
            ],
            // event
            [
                'id_paket' => 25,
                'nama_paket' => 'Event Package',
                'harga_paket' => 500000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'Unlimited',
                'jumlah_foto_edit' => '20 photo edited',
                'cetak_foto' => 'Cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'Indoor only',
                'deskripsi_paket'  => 'Fotografi event adalah jenis fotografi yang berkaitan dengan dokumentasi acara atau kegiatan tertentu, seperti konferensi, seminar, pameran, konser, atau acara sosial lainnya. Fotografer event bertanggung jawab untuk menangkap momen-momen penting selama acara, seperti pembicara utama, penampilan musik, atau momen interaksi antara tamu undangan.',
            ],
            // engagement
            [
                'id_paket' => 26,
                'nama_paket' => 'Engagement Standard Package Photo',
                'harga_paket' => 1000000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 1x 12RS + Frame & Cetak 5x 10RS',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi engagement adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya.',
            ],
            [
                'id_paket' => 27,
                'nama_paket' => 'Engagement Glamour Package Photo + Video',
                'harga_paket' => 1500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 1x 12RS + Frame & Cetak 5x 10RS & Cetak 20x 4R',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi engagement adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya.',
            ],
            // couple
            [
                'id_paket' => 28,
                'nama_paket' => 'Couple Package',
                'harga_paket' => 250000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => '5 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => 'Photoshoot couple adalah sesi pemotretan yang dilakukan untuk pasangan sebagai bentuk merayakan cinta, keintiman, dan hubungan mereka. Sesi ini bertujuan untuk mengabadikan momen romantis dan menggambarkan ikatan emosional antara dua orang yang saling mencintai.',
            ],
        ];

        $this->db->table('paket')->insertBatch($data);
    }
}
