<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Paket extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_paket' => 1,
                'nama_paket' => 'PreWedding',
                'warna_nama_paket' => '#ff4d4d',
                'gambar_paket' => 'prewedding-2.png',
                'harga_paket' => 1100000,
                'keterangan_harga_paket' => 2,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 0,
                'waktu' => 4,
                'dua_tempat' => false,
                'tempat_indoor' => 2,
                'tempat_outdoor' => 2,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => false,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive.',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            [
                'id_paket' => 2,
                'nama_paket' => 'Wedding',
                'warna_nama_paket' => '#ce7e26',
                'gambar_paket' => 'wedding-2.png',
                'harga_paket' => 1750000,
                'keterangan_harga_paket' => 2,
                'status_paket' => '1',
                'fotografer' => 2,
                'videografer' => 1,
                'waktu' => 4,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 0,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => true,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 3,
                'nama_paket' => 'Maternity',
                'warna_nama_paket' => '#e08d89',
                'gambar_paket' => 'prewedding-3.png',
                'harga_paket' => 1400000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 1,
                'waktu' => 3,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 1,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => true,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi maternity adalah jenis fotografi yang berkaitan dengan kehamilan, di mana seorang ibu hamil akan diabadikan dalam foto-foto yang indah dan artistik. Fotografi ini dilakukan pada trimester ketiga kehamilan, saat perut sudah membesar dan bentuk tubuh ibu hamil semakin menonjol. Fotografer maternity bertanggung jawab untuk menangkap momen-momen indah dan mengesankan selama masa kehamilan, termasuk saat ibu hamil bersama pasangannya, saat mempersiapkan kamar bayi, atau bahkan saat sedang melakukan aktivitas sehari-hari. Fotografer juga akan membimbing ibu hamil dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, ibu hamil dan keluarganya dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi maternity membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakn suasana yang nyaman dan tenang untuk ibu hamil sehingga bisa menghasilkan foto-foto yang indah dan mengesankan.',
            ],
            [
                'id_paket' => 4,
                'nama_paket' => 'Family',
                'warna_nama_paket' => '#e2bc72',
                'gambar_paket' => 'family-3.png',
                'harga_paket' => 750000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 0,
                'waktu' => 2,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 0,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => false,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi keluarga adalah jenis fotografi yang berkaitan dengan momen-momen berharga antara anggota keluarga, di mana keluarga akan diabadikan dalam foto-foto yang indah dan mengesankan. Fotografi ini bisa dilakukan dalam berbagai acara atau kesempatan, seperti ulang tahun, perayaan Natal atau Tahun Baru, liburan keluarga, atau bahkan hanya saat berkumpul bersama di rumah. Fotografer keluarga bertanggung jawab untuk menangkap momen-momen penting selama sesi pemotretan, seperti saat keluarga sedang bersenang-senang bersama, bercanda, atau berpelukan. Fotografer juga akan membimbing keluarga dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, keluarga dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi keluarga membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakan suasana yang nyaman dan akrab sehingga bisa menghasilkan foto-foto yang indah dan penuh makna bagi keluarga.',
            ],
            [
                'id_paket' => 5,
                'nama_paket' => 'Birthday Party',
                'warna_nama_paket' => '#8489cb',
                'gambar_paket' => 'birthday-1.png',
                'harga_paket' => 900000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 0,
                'waktu' => 4,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 0,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => false,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi ulang tahun adalah jenis fotografi yang berkaitan dengan momen-momen perayaan ulang tahun, di mana orang yang berulang tahun akan diabadikan dalam foto-foto yang mengesankan. Fotografi ini dilakukan pada saat acara ulang tahun, baik itu di dalam ruangan atau di luar ruangan. Fotografer ulang tahun bertanggung jawab untuk menangkap momen-momen penting selama acara, seperti saat sang ulang tahun memotong kue, membuka kado, atau bersenang-senang bersama tamu undangan. Fotografer juga akan membimbing sang ulang tahun dan tamu undangan dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah acara selesai, tamu undangan dapat memilih foto-foto favorit mereka untuk diabadikan sebagai kenang-kenangan. Fotografi ulang tahun membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menghadapi berbagai kondisi pencahayaan dan menangkap momen-momen penting dengan cepat dan tepat.',
            ],
            [
                'id_paket' => 6,
                'nama_paket' => 'Group',
                'warna_nama_paket' => '#a44473',
                'gambar_paket' => 'group-2.png',
                'harga_paket' => 750000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 0,
                'waktu' => 2,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 0,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => true,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi grup adalah jenis fotografi yang berkaitan dengan memotret sekelompok orang dalam satu bingkai foto. Fotografi grup bisa dilakukan dalam berbagai konteks, seperti dalam acara keluarga, acara sekolah, acara perusahaan, atau bahkan dalam acara publik. Fotografer grup bertanggung jawab untuk menangkap momen-momen penting selama sesi pemotretan, seperti momen kebersamaan, keakraban, dan kegembiraan antara para anggota grup. Fotografer juga akan membimbing anggota grup dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, anggota grup dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi grup membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakan suasana yang nyaman dan akrab sehingga bisa menghasilkan foto-foto yang indah dan penuh makna bagi para anggota grup.',
            ],
            [
                'id_paket' => 7,
                'nama_paket' => 'Graduation',
                'warna_nama_paket' => '#ded01b',
                'gambar_paket' => 'graduation.png',
                'harga_paket' => 750000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 1,
                'videografer' => 0,
                'waktu' => 2,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 0,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => false,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi kelulusan adalah jenis fotografi yang berkaitan dengan momen kelulusan, di mana para siswa yang telah menyelesaikan sekolah atau perguruan tinggi akan diabadikan dalam foto resmi. Fotografi ini biasanya dilakukan pada saat upacara kelulusan atau beberapa waktu setelahnya. Fotografer kelulusan bertanggung jawab untuk menangkap momen-momen penting pada saat kelulusan, seperti saat para siswa menerima ijazah mereka, berpose bersama keluarga dan teman-teman, dan saat memakai toga dan topi kelulusan. Fotografer kelulusan juga akan membimbing para siswa dalam pose-pose yang baik dan menarik, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, para siswa dan keluarga dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi kelulusan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menghadapi berbagai kondisi pencahayaan dan menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 8,
                'nama_paket' => 'Event',
                'warna_nama_paket' => '#4273a0',
                'gambar_paket' => 'event-1.png',
                'harga_paket' => 1900000,
                'keterangan_harga_paket' => 1,
                'status_paket' => '0',
                'fotografer' => 2,
                'videografer' => 1,
                'waktu' => 4,
                'dua_tempat' => false,
                'tempat_indoor' => 1,
                'tempat_outdoor' => 1,
                'hasil_jumlah' => 2,
                'hasil_ukuran_cetak' => '30 x 40',
                'hasil_editing' => 3,
                'hasil_cinematic' => true,
                'kapasitas' => 'Unlimited soft file mentah dikirim Gdrive',
                'deskripsi_paket'  => 'Fotografi event adalah jenis fotografi yang berkaitan dengan dokumentasi acara atau kegiatan tertentu, seperti konferensi, seminar, pameran, konser, atau acara sosial lainnya. Fotografer event bertanggung jawab untuk menangkap momen-momen penting selama acara, seperti pembicara utama, penampilan musik, atau momen interaksi antara tamu undangan. Fotografer juga akan memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi, serta mampu menangkap esensi dari acara tersebut. Fotografer event harus memahami dinamika acara dan kemampuan untuk mengantisipasi momen-momen penting yang akan terjadi selama acara berlangsung. Setelah acara selesai, foto-foto yang diambil akan diedit dan dipilih untuk digunakan dalam laporan acara atau sebagai dokumentasi acara tersebut. Fotografi event membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk beradaptasi dengan berbagai kondisi pencahayaan dan situasi yang mungkin terjadi selama acara berlangsung.',
            ],
        ];

        $this->db->table('paket')->insertBatch($data);
    }
}
