<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Paket extends Seeder
{
    public function run()
    {
        $data = [
            // prewedding
            [
                'id_paket' => 1,
                'nama_paket' => 'Pre-Wedding Package Indoor',
                'harga_paket' => 450000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '60-90 menit',
                'jumlah_foto' => '60-120 foto',
                'jumlah_foto_edit' => '15 foto edit',
                'cetak_foto' => 'Cetak 10RS 5 lembar & Cetak 12RS + frame 1 lembar',
                'videografi' => '',
                'penyimpanan' => 'All softfile via Gdrive dihari yang sama',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            [
                'id_paket' => 2,
                'nama_paket' => 'Pre-Wedding Outdoor Package A Photo',
                'harga_paket' => 1000000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '50 photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            [
                'id_paket' => 3,
                'nama_paket' => 'Pre-Wedding Outdoor Package B Photo',
                'harga_paket' => 1500000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '4 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            [
                'id_paket' => 4,
                'nama_paket' => 'Pre-Wedding Outdoor Package C Photo + Video',
                'harga_paket' => 2500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Cetak 12RS + Frame',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            [
                'id_paket' => 5,
                'nama_paket' => 'Pre-Wedding Outdoor Package D Photo + Video',
                'harga_paket' => 3500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Cetak 16RS + Frame',
                'videografi' => '3 minute cinematic video, video drone',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => "Fotografi pre-wedding adalah sesi pemotretan foto yang dilakukan oleh pasangan calon pengantin sebelum hari pernikahan mereka. Tujuannya adalah untuk menciptakan kenangan dan dokumentasi sebelum pernikahan, serta menghasilkan foto-foto yang bisa digunakan untuk undangan pernikahan, album foto, atau bahkan dekorasi pernikahan. Fotografi pre-wedding biasanya dilakukan di tempat-tempat indah, seperti taman, pantai, gunung, atau kota-kota dengan pemandangan yang menarik. Pasangan calon pengantin biasanya memilih tema dan konsep tertentu, serta mengenakan pakaian khusus yang sesuai dengan tema tersebut. Fotografer pre-wedding bertanggung jawab untuk menangkap momen-momen romantis dan natural antara pasangan calon pengantin, serta memastikan bahwa setiap foto terlihat indah dan menawan. Mereka juga menggunakan teknik fotografi yang kreatif dan unik untuk menghasilkan foto-foto yang unik dan memukau. Fotografi pre-wedding membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk membimbing pasangan calon pengantin dalam pose-pose yang menarik dan natural.",
            ],
            // wedding
            ////akad
            [
                'id_paket' => 6,
                'nama_paket' => 'Akad Simple Package',
                'harga_paket' => 1350000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 25 lembar (4R) & Cetak 1x 12RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 7,
                'nama_paket' => 'Akad Premium Package',
                'harga_paket' => 1750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 8,
                'nama_paket' => 'Akad Exclusive Package',
                'harga_paket' => 2250000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '6 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Magnetic Album + 120 photo (4R)',
                'videografi' => '1 minute cinematic video',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            ////resepsi
            [
                'id_paket' => 9,
                'nama_paket' => 'Resepsi Bronze Package',
                'harga_paket' => 1750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 10,
                'nama_paket' => 'Resepsi Silver Package Resepsi + Temu',
                'harga_paket' => 2150000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '8 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 100 photo (4R)',
                'videografi' => '',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 11,
                'nama_paket' => 'Resepsi Gold Package Resepsi + Akad',
                'harga_paket' => 2750000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '7 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Premium Magazine & print 16RS + Frame',
                'videografi' => '',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 12,
                'nama_paket' => 'Resepsi Platinum Package Resepsi + Akad',
                'harga_paket' => 3000000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '7 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => '150 photo edited',
                'cetak_foto' => 'Magnetic Album + 120 photo (4R)',
                'videografi' => '1 minute video teaser',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 13,
                'nama_paket' => 'Resepsi Titanium Package Resepsi + Akad',
                'harga_paket' => 4000000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '8 working hours',
                'jumlah_foto' => 'Unlimited photo',
                'jumlah_foto_edit' => 'All photo edited',
                'cetak_foto' => 'Premium Magazine',
                'videografi' => '1 minute video teaser & 3 minute video highlight',
                'penyimpanan' => 'All files in USB Flashdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi pernikahan adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            // personal
            [
                'id_paket' => 14,
                'nama_paket' => 'Personal Package',
                'harga_paket' => 600000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'unlimited',
                'jumlah_foto_edit' => 'All photos edited tone',
                'cetak_foto' => '2 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '', 'deskripsi_paket'  => 'Fotografi grup adalah jenis fotografi yang berkaitan dengan memotret sekelompok orang dalam satu bingkai foto. Fotografi grup bisa dilakukan dalam berbagai konteks, seperti dalam acara keluarga, acara sekolah, acara perusahaan, atau bahkan dalam acara publik. Fotografer grup bertanggung jawab untuk menangkap momen-momen penting selama sesi pemotretan, seperti momen kebersamaan, keakraban, dan kegembiraan antara para anggota grup. Fotografer juga akan membimbing anggota grup dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, anggota grup dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi grup membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakan suasana yang nyaman dan akrab sehingga bisa menghasilkan foto-foto yang indah dan penuh makna bagi para anggota grup.',
            ],
            // group
            [
                'id_paket' => 15,
                'nama_paket' => 'Group Package',
                'harga_paket' => 600000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'unlimited',
                'jumlah_foto_edit' => 'All photos edited tone',
                'cetak_foto' => '2 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi grup adalah jenis fotografi yang berkaitan dengan memotret sekelompok orang dalam satu bingkai foto. Fotografi grup bisa dilakukan dalam berbagai konteks, seperti dalam acara keluarga, acara sekolah, acara perusahaan, atau bahkan dalam acara publik. Fotografer grup bertanggung jawab untuk menangkap momen-momen penting selama sesi pemotretan, seperti momen kebersamaan, keakraban, dan kegembiraan antara para anggota grup. Fotografer juga akan membimbing anggota grup dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, anggota grup dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi grup membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakan suasana yang nyaman dan akrab sehingga bisa menghasilkan foto-foto yang indah dan penuh makna bagi para anggota grup.',
            ],
            // maternity
            [
                'id_paket' => 16,
                'nama_paket' => 'Maternity Package',
                'harga_paket' => 250000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => '5 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => 'Fotografi maternity adalah jenis fotografi yang berkaitan dengan kehamilan, di mana seorang ibu hamil akan diabadikan dalam foto-foto yang indah dan artistik. Fotografi ini dilakukan pada trimester ketiga kehamilan, saat perut sudah membesar dan bentuk tubuh ibu hamil semakin menonjol. Fotografer maternity bertanggung jawab untuk menangkap momen-momen indah dan mengesankan selama masa kehamilan, termasuk saat ibu hamil bersama pasangannya, saat mempersiapkan kamar bayi, atau bahkan saat sedang melakukan aktivitas sehari-hari. Fotografer juga akan membimbing ibu hamil dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, ibu hamil dan keluarganya dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi maternity membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakn suasana yang nyaman dan tenang untuk ibu hamil sehingga bisa menghasilkan foto-foto yang indah dan mengesankan.',
            ],
            // graduation
            [
                'id_paket' => 17,
                'nama_paket' => 'Graduation Package',
                'harga_paket' => 350000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'Unlimited',
                'jumlah_foto_edit' => '15 photo edited',
                'cetak_foto' => '',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi kelulusan adalah jenis fotografi yang berkaitan dengan momen kelulusan, di mana para siswa yang telah menyelesaikan sekolah atau perguruan tinggi akan diabadikan dalam foto resmi. Fotografi ini biasanya dilakukan pada saat upacara kelulusan atau beberapa waktu setelahnya. Fotografer kelulusan bertanggung jawab untuk menangkap momen-momen penting pada saat kelulusan, seperti saat para siswa menerima ijazah mereka, berpose bersama keluarga dan teman-teman, dan saat memakai toga dan topi kelulusan. Fotografer kelulusan juga akan membimbing para siswa dalam pose-pose yang baik dan menarik, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, para siswa dan keluarga dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi kelulusan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menghadapi berbagai kondisi pencahayaan dan menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            // family
            [
                'id_paket' => 18,
                'nama_paket' => 'Family Package',
                'harga_paket' => 275000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => 'Cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'Indoor only',
                'deskripsi_paket'  => 'Fotografi keluarga adalah jenis fotografi yang berkaitan dengan momen-momen berharga antara anggota keluarga, di mana keluarga akan diabadikan dalam foto-foto yang indah dan mengesankan. Fotografi ini bisa dilakukan dalam berbagai acara atau kesempatan, seperti ulang tahun, perayaan Natal atau Tahun Baru, liburan keluarga, atau bahkan hanya saat berkumpul bersama di rumah. Fotografer keluarga bertanggung jawab untuk menangkap momen-momen penting selama sesi pemotretan, seperti saat keluarga sedang bersenang-senang bersama, bercanda, atau berpelukan. Fotografer juga akan membimbing keluarga dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, keluarga dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi keluarga membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakan suasana yang nyaman dan akrab sehingga bisa menghasilkan foto-foto yang indah dan penuh makna bagi keluarga.',
            ],
            // event
            [
                'id_paket' => 19,
                'nama_paket' => 'Event Package',
                'harga_paket' => 500000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '2 working hours',
                'jumlah_foto' => 'Unlimited',
                'jumlah_foto_edit' => '20 photo edited',
                'cetak_foto' => 'Cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'Indoor only',
                'deskripsi_paket'  => 'Fotografi event adalah jenis fotografi yang berkaitan dengan dokumentasi acara atau kegiatan tertentu, seperti konferensi, seminar, pameran, konser, atau acara sosial lainnya. Fotografer event bertanggung jawab untuk menangkap momen-momen penting selama acara, seperti pembicara utama, penampilan musik, atau momen interaksi antara tamu undangan. Fotografer juga akan memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi, serta mampu menangkap esensi dari acara tersebut. Fotografer event harus memahami dinamika acara dan kemampuan untuk mengantisipasi momen-momen penting yang akan terjadi selama acara berlangsung. Setelah acara selesai, foto-foto yang diambil akan diedit dan dipilih untuk digunakan dalam laporan acara atau sebagai dokumentasi acara tersebut. Fotografi event membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk beradaptasi dengan berbagai kondisi pencahayaan dan situasi yang mungkin terjadi selama acara berlangsung.',
            ],
            // engagement
            [
                'id_paket' => 20,
                'nama_paket' => 'Engagement Standard Package Photo',
                'harga_paket' => 1000000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '3 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 1x 12RS + Frame & Cetak 5x 10RS',
                'videografi' => '',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi engagement adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            [
                'id_paket' => 21,
                'nama_paket' => 'Engagement Glamour Package Photo + Video',
                'harga_paket' => 1500000,
                'fotografer' => 1,
                'videografer' => 1,
                'asisten' => 1,
                'waktu_kerja' => '5 working hours',
                'jumlah_foto' => '150 photo',
                'jumlah_foto_edit' => '100 photo edited',
                'cetak_foto' => 'Cetak 1x 12RS + Frame & Cetak 5x 10RS & Cetak 20x 4R',
                'videografi' => '1 minute Cinematic Video',
                'penyimpanan' => 'All files in CD Drive',
                'note' => '',
                'deskripsi_paket'  => 'Fotografi engagement adalah seni dan praktik fotografi yang mengkhususkan diri dalam pemotretan pernikahan. Fotografer pernikahan bertanggung jawab untuk menangkap momen-momen penting pada hari pernikahan, termasuk saat pengantin sedang bersiap-siap, upacara pernikahan, resepsi, dan acara-acara terkait pernikahan lainnya. Mereka juga bertugas untuk mengambil gambar potret pengantin dan keluarga, serta memastikan bahwa setiap momen penting diabadikan dalam foto yang berkualitas tinggi. Fotografer pernikahan harus mampu menghadapi berbagai kondisi pencahayaan, memanfaatkan teknik fotografi yang tepat, serta mampu membimbing pengantin dan keluarga dalam pose-pose yang menarik dan natural. Setelah pemotretan, fotografer akan mengedit dan menghasilkan foto-foto yang siap untuk dicetak dan dibagikan. Fotografi pernikahan membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menangkap momen-momen penting dengan tepat dan artistik.',
            ],
            // couple
            [
                'id_paket' => 22,
                'nama_paket' => 'Couple Package',
                'harga_paket' => 250000,
                'fotografer' => 1,
                'videografer' => 0,
                'asisten' => 1,
                'waktu_kerja' => '30-50 minute',
                'jumlah_foto' => '30-80 photo',
                'jumlah_foto_edit' => '5 photo edited',
                'cetak_foto' => '5 cetak 10RS',
                'videografi' => '',
                'penyimpanan' => 'All Softfile via Gdrive',
                'note' => 'bawa sendiri',
                'deskripsi_paket'  => 'Fotografi maternity adalah jenis fotografi yang berkaitan dengan kehamilan, di mana seorang ibu hamil akan diabadikan dalam foto-foto yang indah dan artistik. Fotografi ini dilakukan pada trimester ketiga kehamilan, saat perut sudah membesar dan bentuk tubuh ibu hamil semakin menonjol. Fotografer maternity bertanggung jawab untuk menangkap momen-momen indah dan mengesankan selama masa kehamilan, termasuk saat ibu hamil bersama pasangannya, saat mempersiapkan kamar bayi, atau bahkan saat sedang melakukan aktivitas sehari-hari. Fotografer juga akan membimbing ibu hamil dalam pose-pose yang menarik dan natural, serta memastikan bahwa setiap foto terlihat indah dan berkualitas tinggi. Setelah sesi pemotretan selesai, ibu hamil dan keluarganya dapat memilih foto-foto favorit mereka untuk dicetak dan dibagikan sebagai kenang-kenangan. Fotografi maternity membutuhkan keterampilan teknis yang tinggi, ketelitian, serta kemampuan untuk menciptakn suasana yang nyaman dan tenang untuk ibu hamil sehingga bisa menghasilkan foto-foto yang indah dan mengesankan.',
            ],
        ];

        $this->db->table('paket')->insertBatch($data);
    }
}
