<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Pesanan extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_pesanan' => 1,
                'id_user' => 2,
                'id_paket' => 19,
                'nama_lengkap' => 'Angga',
                'tanggal_mulai' => '2023-07-21 13:55:00',
                'tanggal_selesai' => '2023-07-21 16:55:00',
                'telp' => '082112344321',
                'alamat'  => 'Malang',
                'catatan' => '',
                'extra_waktu_kerja' => '0',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '0',
                'extra_wisudawan' => '0',
            ],
            [
                'id_pesanan' => 4,
                'id_user' => 2,
                'id_paket' => 17,
                'nama_lengkap' => 'Azhar Maulana',
                'tanggal_mulai' => '2023-08-24 17:53:00',
                'tanggal_selesai' => '2023-08-24 19:53:00',
                'telp' => '082112344321',
                'alamat'  => 'Singosari',
                'catatan' => '',
                'extra_waktu_kerja' => '0',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '36',
                'extra_wisudawan' => '0',
            ],
            [
                'id_pesanan' => 5,
                'id_user' => 2,
                'id_paket' => 17,
                'nama_lengkap' => 'Azhar Maulana',
                'tanggal_mulai' => '2023-07-21 10:30:00',
                'tanggal_selesai' => '2023-07-21 12:30:00',
                'telp' => '082112344321',
                'alamat'  => 'Singosari',
                'catatan' => '',
                'extra_waktu_kerja' => '0',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '0',
                'extra_wisudawan' => '0',
            ],
            [
                'id_pesanan' => 11,
                'id_user' => 2,
                'id_paket' => 19,
                'nama_lengkap' => 'user saya',
                'tanggal_mulai' => '2023-07-27 15:30:00',
                'tanggal_selesai' => '2023-07-27 17:30:00',
                'telp' => '082112344321',
                'alamat'  => 'Singosari',
                'catatan' => '',
                'extra_waktu_kerja' => '1',
                'extra_premium_magazine' => '0',
                'extra_background' => '1',
                'extra_tempat' => '0',
                'extra_orang' => '1',
                'extra_wisudawan' => '1',
            ],
            [
                'id_pesanan' => 12,
                'id_user' => 2,
                'id_paket' => 21,
                'nama_lengkap' => 'user saya',
                'tanggal_mulai' => '2023-08-24 08:32:00',
                'tanggal_selesai' => '2023-08-24 12:32:00',
                'telp' => '082112344321',
                'alamat'  => 'jl. raya gadang',
                'catatan' => '',
                'extra_waktu_kerja' => '0',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '2',
                'extra_wisudawan' => '1',
            ],
            [
                'id_pesanan' => 13,
                'id_user' => 2,
                'id_paket' => 10,
                'nama_lengkap' => 'user saya',
                'tanggal_mulai' => '2023-08-24 08:32:00',
                'tanggal_selesai' => '2023-08-24 12:32:00',
                'telp' => '082112344321',
                'alamat'  => 'Jl. Sugeng Rawuh',
                'catatan' => '',
                'extra_waktu_kerja' => '1',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '0',
                'extra_wisudawan' => '0',
            ],
            [
                'id_pesanan' => 14,
                'id_user' => 2,
                'id_paket' => 18,
                'nama_lengkap' => 'user saya',
                'tanggal_mulai' => '2023-08-24 13:49:00',
                'tanggal_selesai' => '2023-08-24 15:49:00',
                'telp' => '082112344321',
                'alamat'  => 'Jl. Kemanggi',
                'catatan' => '',
                'extra_waktu_kerja' => '1',
                'extra_premium_magazine' => '0',
                'extra_background' => '2',
                'extra_tempat' => '0',
                'extra_orang' => '0',
                'extra_wisudawan' => '0',
            ],
            [
                'id_pesanan' => 15,
                'id_user' => 2,
                'id_paket' => 18,
                'nama_lengkap' => 'user saya',
                'tanggal_mulai' => '2023-08-25 11:20:00',
                'tanggal_selesai' => '2023-08-25 15:20:00',
                'telp' => '082112344321',
                'alamat'  => 'jl kemakmuran',
                'catatan' => '',
                'extra_waktu_kerja' => '2',
                'extra_premium_magazine' => '0',
                'extra_background' => '0',
                'extra_tempat' => '0',
                'extra_orang' => '0',
                'extra_wisudawan' => '0',
            ],
        ];

        $this->db->table('pesanan')->insertBatch($data);
    }
}
